### ISSUE TITLE
Cucumber tests unable to run

### ISSUE THREAD

**Issue by sethlesky** [thereactivestack/kickstart-meteor-react-router#20]
After adding the cucumber package, and running metoer

    meteor add xolvio:cucumber
    meteor

I get the following error in cucumber.log

     @focus
     Scenario: This scenario will run on both dev and CI   # features/sample.feature:20
       Given I am a new user                               # features/sample.feature:16
      Error: Method not found [404]
          (No stack trace)
      From previous event:
        at World.<anonymous> (features/step_definitions/sample_steps.js:10:12)

Commenting our `server.call('reset');` in sample_steps.js removes the error, and allows the test to pass if sample.feature is properly adjusted.

Possibly related is that running tests against the dynamically loaded AdminApp doesn't work. When accessing the mirrored meteor (http://localhost:49870/). Clicking 'admin' updates the url but doesn't load the view.

The following error in chrome dev tools is appears when clicking the 'admin' link

    Uncaught TypeError: Cannot read property 'call' of undefined__webpack_require__ 
    @ bootstrap e66aaadfa0b0aacd66ee:47(anonymous function) @ index.js:17webpackJsonpCallback 
    @ bootstrap e66aaadfa0b0aacd66ee:18(anonymous function) @ 1.web.js:12browser.js:49 
    
    Warning: Location "/admin/dashboard" did not match any routes

Thanks so much for putting together such an awesome meteor-react-webpack starter! Apologies if I've missed something obvious, I'm new to this stack.

**Comment by cryptoquick** [comment]
`server.call` is calling a Meteor method, which is supposed to be for calling a fixture for Chimp's Cucumber implementation.

If you look at the documentation on this package, you'll notice that everything needs to be required from an entry context.

So, this ticket is really asking:

Can Chimp-style Cucumber server fixtures be run, and do they have to be called in the same way that the Jasmine integration tests are being called for each module?

I'm worried that the module-oriented approach, while superior, does not lend itself well to the way Chimp currently implements Cucumber integration tests.

**Comment by cryptoquick** [comment]
I believe I've answered my own question. The answer appears to be, yes, fixtures can be written within modules, while Cucumber tests and step definitions can be placed within the top-level tests directory.

This will work for now, but I suspect `entry.js` could even be modified to allow Cucumber tests to be written on a per-module basis, much like the Jasmine tests are.

**Comment by eXon** [comment]
I haven't tried cucumber yet with Webpack but it was planned to support them. I'll take a look when I have some time for this.

**Comment by cryptoquick** [comment]
Awesome, I'm looking forward to seeing what you might come up with. For now, from what I've seen, as long as fixtures are added as part of the modules-based tests, adding Cucumber tests just as described throughout the thread should work just fine. Thanks!

**Comment by eXon** [comment]
I'm closing this because tests are going to be supported the new way
