### ISSUE TITLE
Can't start karma [has workaround]

### ISSUE THREAD

**Issue by myknbani** [thereactivestack/kickstart-meteor-react-router#24]
Thanks for this awesome repo!  :D

For some reason running this project out-of-the-box or after every reboot of my PC results in the following:

```
20151126-05:58:43.697(8)? (STDERR) [sanjo:karma]: start request failed { [Error: connect ECONNREFUSED]
W20151126-05:58:43.698(8)? (STDERR)   code: 'ECONNREFUSED',
W20151126-05:58:43.698(8)? (STDERR)   errno: 'ECONNREFUSED',
W20151126-05:58:43.698(8)? (STDERR)   syscall: 'connect' }
```

As a result, client unit tests do not run.  For the meantime, my workaround is to let jasmine and karma activate from a non-webpack dummy project.  Then stop the dummy and run this kickstart.

**Comment by eXon** [comment]
This is weird I never had this problem. On what OS are you? Do you still have the problem?

**Comment by myknbani** [comment]
Yes still the same problem.  I currently don't mind though.  It is the Velocity tests-that-are-not-refreshing bug, reported in the kickstart-simple repo that's really bugging me. Hehe...

I'm on Linux, Fedora 23, 64-bit.  
`4.2.3-300.fc23.x86_64` kernel

For this issue, once Karma has started, things are fine the rest of the way.

```
I20151214-07:43:18.842(8)? [velocity] Mirror process forked with pid 23932
I20151214-07:43:18.842(8)? [velocity] jasmine-server-integration is starting a mirror at http://localhost:33825/.
I20151214-07:43:18.842(8)? [velocity] You can see the mirror logs at: tail -f /home/mykeenbani/Documents/thesis/oppinut-kickstart/.meteor/local/log/jasmine-server-integration.log
W20151214-07:43:22.945(8)? (STDERR) [sanjo:karma]: start request failed { [Error: connect ECONNREFUSED]
W20151214-07:43:22.946(8)? (STDERR)   code: 'ECONNREFUSED',
W20151214-07:43:22.946(8)? (STDERR)   errno: 'ECONNREFUSED',
W20151214-07:43:22.946(8)? (STDERR)   syscall: 'connect' }
```

**Comment by eXon** [comment]
Do you only have jasmine tests or also cucumber?

**Comment by myknbani** [comment]
Yes I have cucumber as well.

**Comment by chip** [comment]
I have this same issue when running `meteor run ios`.

**Comment by tyagiakhilesh** [comment]
I also get this issue when I start running my meteor project. I only have jasmine tests, with velocity. I am only ubuntu 64bit Linux. But for me this problem goes away if I cancel the last try and restart again.

**Comment by namerci** [comment]
I have same on Ubuntu 14.04 64bit in VM.

**Comment by tahaykNSM** [comment]
I have the same problem on Ubuntu 14, 
The problem goes away when I cancel the last try and restart.
but I always get the same problem when I try to use `PhantomJS` as the Karma browser.

**Comment by edwardupton** [comment]
I get the same issue, but only after updating to Meteor 1.3
I'm on OS X.11.2 with my default browser (the one Karma used to use) set as Chrome

**Comment by brylie** [comment]
Same issue here after updating to Meteor 1.3. We are testing on multiple OSs, but my personal development environment is Ubuntu 16.04 x64.

**Comment by eXon** [comment]
This has not been yet tested but unit tests are coming!
