### ISSUE TITLE
Example does not make it clear where all things should go

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-meteor-react-router#26]
The example only has methods for one of the apps and they are loaded in entry. If the AdminApp also has methods, would those be imported in Entry as well? What about shared methods and/or collections? Do you advise importing across 'Apps' or creating a "common" folder or something in the root to hold shared pieces? 

Also what about shared routes across apps? Do you suggest duplicating them in two different route files? It would help if the HugeApp was actually huge and showed how best to handle these situations. We LOVE this stack and hope to keep using it, but we're spending a lot of time with trial and error trying to figure out basic things like these.

Thanks.

**Comment by D1no** [comment]
What would be a good prototype, huge app? A clone of something?

**Comment by eXon** [comment]
You will be delighted by what's coming soon :) I can't tell more for now

**Comment by sethlesky** [comment]
Looking forward to it @eXon :+1:

**Comment by CEOGavin** [comment]
Any ETA on what's 'coming soon' @eXon ? :)

**Comment by fuatsengul** [comment]
Any news on that? @eXon 
I'm desperately waiting for this...

**Comment by eXon** [comment]
ETA is in 7 days (march 1st). Pretty sure it be ready :)

**Comment by dbismut** [comment]
Hey @eXon, can you tell at this stage if it includes redux?

**Comment by tomitrescak** [comment]
Looking forward! :+1:

**Comment by eXon** [comment]
@dbismut There already is an example of using redux with react-router. It should continue to work with meteor-webpack without any problem. I'll probably write a tutorial about it on the future.

**Comment by dbismut** [comment]
Damn I really can't wait.

I'm in the middle of a project using your framework, and it already works very well. I've updated react-router to use react-router 2.0 (also removing `ReactRouter.history = require('history')` and react-router-ssr so that it uses the new history singleton from react-router 2.0.

I'm also using middlewares inspired from this [repo](https://github.com/djhi/my-nutrition) for redux so I don't get to use `getMeteorData`.

Anyway, looking forward to March 1st :)

**Comment by eXon** [comment]
Really have to update react-router-ssr to work with react-router 2.0. I've been so busy in 2016 I hope I'll find more time to work on Meteor projects.

**Comment by dbismut** [comment]
I can try pushing a Pull Request if you want (it's no big deal as far as I can tell). It would also be cool to have a way to pass the redux store as a parameter to routes... ! That would allow easier management of auth (at least in my situation).

Good luck with your projects, and thanks for everything.

**Comment by eXon** [comment]
They removed the RoutingContext in 2.0 (it was undocumented) and I have to figure out how to do the same without it. If you know how I'll be happy to look at your solution.

**Comment by dbismut** [comment]
Well, it's now simply replaced by RouterContext, I didn't have much to do... Unless I missed something?
https://github.com/reactjs/react-router/blob/master/docs/API.md

There's one thing that might be a bit tricky, it's the new 4.0.0 for redux-simple-router, which would needs the store to connect the history that would be then passed to the `<Router>`. I'm sticking to 3.0.0 for now.

**Comment by eXon** [comment]
Let me know if something is still missing
