### ISSUE TITLE
Navigating Outside of Components

### ISSUE THREAD

**Issue by maciejmyslinski** [thereactivestack/kickstart-meteor-react-router#40]
Hi!
I use alt flux implementation in my app. I would like to do something like this in my store:
```javascript
history.pushState(null, url)
```
The thing is, [to navigate outside my components](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/NavigatingOutsideOfComponents.md) I have to export my history object and then import it both to store and to `/entry/client/routes.jsx` file.
I created `/modules/sharedHistory.js`:
```javascript
import createBrowserHistory from 'history/lib/createBrowserHistory'
export default createBrowserHistory()
```
My `/entry/client/routes.jsx` file:
```javascript
import sharedHistory from 'sharedHistory'

ReactRouterSSR.Run({
  childRoutes: [
    require('Auth/client'),
    require('App/client'),
  ]
}, {
  history: sharedHistory
})
```
In development everything works, but in production I have errors:
```bash
W20151225-11:34:54.543(1)? (STDERR)
W20151225-11:34:54.544(1)? (STDERR) /Users/Maciej/.meteor/packages/meteor-tool/.1.1.10.1mi2tyy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151225-11:34:54.544(1)? (STDERR) 						throw(ex);
W20151225-11:34:54.544(1)? (STDERR) 						      ^
W20151225-11:34:54.589(1)? (STDERR)     at Object.e (webpack:///Users/Maciej/Projects/robsonGO/modules/App/client/components/GoogleMaps/utils/controlledPropTypes/mapControlledPropTypes.js:9:24)
W20151225-11:34:54.589(1)? (STDERR)     at Object.o [as default] (webpack:///Users/Maciej/Projects/robsonGO/.meteor/local/webpack-npm/~/scriptjs/dist/script.js:1:1)
W20151225-11:34:54.589(1)? (STDERR)     at Object.r [as default] (webpack:///Users/Maciej/Projects/robsonGO/modules/App/client/components/GoogleMaps/utils/eventsLists/markerEvents.js:19:3)
W20151225-11:34:54.588(1)? (STDERR) Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
W20151225-11:34:54.591(1)? (STDERR)     at t (webpack:///Users/Maciej/Projects/robsonGO/.meteor/local/webpack-npm/~/alt/lib/store/StoreMixin.js:159:1)
W20151225-11:34:54.592(1)? (STDERR)     at Object.e.__esModule.default (webpack:///Users/Maciej/Projects/robsonGO/.meteor/local/webpack-npm/~/history/lib/createBrowserHistory.js:60:1)
W20151225-11:34:54.592(1)? (STDERR)     at t (webpack:///Users/Maciej/Projects/robsonGO/.meteor/local/webpack-npm/~/alt/lib/store/StoreMixin.js:159:1)
W20151225-11:34:54.592(1)? (STDERR)     at Object.e.exports (webpack:///Users/Maciej/Projects/robsonGO/.meteor/local/webpack-npm/~/alt/lib/store/StoreMixin.js:171:6)
W20151225-11:34:54.592(1)? (STDERR)     at t (webpack:///Users/Maciej/Projects/robsonGO/.meteor/local/webpack-npm/~/alt/lib/store/StoreMixin.js:159:1)
W20151225-11:34:54.592(1)? (STDERR)     at e.exports (webpack:///Users/Maciej/Projects/robsonGO/.meteor/local/webpack-npm/~/alt/lib/store/StoreMixin.js:164:1)
W20151225-11:34:54.592(1)? (STDERR)     at webpack:///Users/Maciej/Projects/robsonGO/.meteor/local/webpack-npm/~/alt/lib/store/StoreMixin.js:164:1
=> Exited with code: 8
```

How to achieve routing outside components in this project?

**Comment by D1no** [comment]
The reason why it fails in production is because in production SSR kicks in and your `client/routes.jsx` is not wrapped in a async. So fiber complaints.

**Comment by maciejmyslinski** [comment]
Thank you @D1no for that advice. Could you prompt me how to wrap `client/routes.jsx` as async function?

**Comment by D1no** [comment]
Upload a small re-production repo and I'll try to take a look at it.

**Comment by maciejmyslinski** [comment]
@D1no [here it is](https://github.com/maciejmyslinski/meteor-flux). It took me a while, sorry.

**Comment by MaksTr** [comment]
@maciejmyslinski I just looked at your repo and will try doing a production run on mup. For now I wanted to ask is this your own flux implementation or is it based on some pattern?

**Comment by maciejmyslinski** [comment]
H! @D1no. I am very glad for your response. As you can see [here](https://github.com/maciejmyslinski/meteor-flux/blob/master/webpack.packages.json#L13) and [there](https://github.com/maciejmyslinski/meteor-flux/blob/master/modules/App/client/alt.js) I am using [alt](http://alt.js.org/) as my flux implementation.

**Comment by Makstr** [comment]
@maciejmyslinski sorry, I can't get it to either. My MupX server just broke down, will update over the weekend and try again

**Comment by maciejmyslinski** [comment]
Hi again @D1no and @Makstr.
I really appreciate all your engagement so far!
Anyway, problem still occurs. Could you take a look at [my repo](https://github.com/maciejmyslinski/meteor-flux) once again?
Best regards.

**Comment by eXon** [comment]
You cannot use the BrowserHistory on the server. You have to use the MemoryHistory but react-router-ssr is already taking care of all that.

I suggest that you go look at the [example with redux](https://github.com/thereactivestack/meteor-react-router-ssr#example-with-redux) of react-router-ssr. You will understand better how it works.
