### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'observe' on 'MutationObserver': The provided node was null.

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-meteor-react-router#48]
Although it does not seem to cause any real issues, the latest hugeapp displays:

'Uncaught NotFoundError: Failed to execute 'observe' on 'MutationObserver': The provided node was null.'

...in the browser console on the initial load. Any idea why?

TIA!

**Comment by eXon** [comment]
Let me know if still a problem
