### ISSUE TITLE
Error Running in Production: "jQuery is not defined"

### ISSUE THREAD

**Issue by john-osullivan** [thereactivestack/kickstart-meteor-react-router#49]
My issue is what's described there -- when I try to run my application in production mode, it throws an error out of one of my components saying jQuery isn't defined.  The stack trace is a little hard to read because of purple on black, but here goes:

![image](https://cloud.githubusercontent.com/assets/3820981/12305488/14fb041a-ba03-11e5-8724-aab59d2e7fcc.png)

Based on the stack trace, it looks like one of my components tries to use jQuery and then the whole application freaks out.  Not sure why this is happening in production but not development.  Any help y'all can offer on why this might be happening would be much appreciated.

**Comment by eXon** [comment]
Add this to your file:

```javascript
import jQuery from 'jquery';
```

It is only crashing in production because your script is loaded after the global.jQuery is defined on development, but not in prod. 

Let me know if it helps

**Comment by john-osullivan** [comment]
Add that line to every file where jQuery gets referenced?  Or to one of the webpack ones?  jQuery is getting used in a lot of places via the `$` syntax.  Is there a way to do the same global.jQuery on production, or is that dangerous?

**Comment by eXon** [comment]
You can do as well:

```javascript
import $ from 'jquery';
```

The global should also work however, I'll be looking into why it doesn't work. If you need to import React everywhere you need it, I don't see why we shouldn't do the same for jquery.

**Comment by john-osullivan** [comment]
Yeah, importing `jQuery` isn't that big of a deal.  Should that only be done in production?  I'm adding that line to every component which uses jQuery, but now the project won't build in development because:

`Error: Cannot resolve module 'jQuery' in ...`

Do I need to install jQuery as an NPM package or something?  Declare it in the externals list in `entry/webpack.conf.js`?

**Comment by eXon** [comment]
If you're having the jquery Meteor package, it should be using it. There is no need to install it from NPM.

**Comment by john-osullivan** [comment]
Yep, I've got `jquery

**Comment by john-osullivan** [comment]
Heads up, I spent a while longer bringing my repo up to date with yours to make sure it wasn't a differing dependency.  I'm now using Babel 6, and everything within my `entry` folder looks essentially like yours.  I added `json` loaders, but that's it.  The project is now running correctly under development settings, but still can't find `jQuery` in production.  It looks like the error gets thrown somehow related to code using `moment.js`:

![image](https://cloud.githubusercontent.com/assets/3820981/12335487/6eb1aa70-bacd-11e5-8d22-ba00d921d52e.png)

**Comment by john-osullivan** [comment]
Hey @eXon , have you had any thoughts on where this bug might be coming from and how I might fix it?  I presume the repo is working fine for you, this jQuery thing is only an issue for me?

**Comment by gothicn** [comment]
In case production mode provides SSR, JQuery is not a accessable on the fly.
The easiest way to get around issues for me is to avoid any dependences and calls to JQuery before component is mounted. And in case i use JQuery only as dependency, i never need to require any dependant modules before actual render.

**Comment by john-osullivan** [comment]
That's probably it, @gothicn , thanks!  I hadn't been writing any jQuery myself outside of `componentDidMount()`, but it looks like `moment` makes use of it.  Going to try swapping out the npm `moment` for the Meteor version and see if that helps.  If not, I'll just activate moment dates from within `componentDidMount()`.

For the sake of asking, do you know of any way to make jQuery accessible from within SSR, or is that not viable because the page won't have rendered in a browser?

**Comment by minfawang** [comment]
@john-osullivan Oh I got a similar error trying to run the project in production mode.
```
=> Exited with code: 8
W20160123-13:46:04.376(-8)? (STDERR)
W20160123-13:46:04.376(-8)? (STDERR) /Root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160123-13:46:04.377(-8)? (STDERR) 						throw(ex);
W20160123-13:46:04.377(-8)? (STDERR) 						      ^
W20160123-13:46:04.684(-8)? (STDERR) TypeError: Object [object Object] has no method 'extend'
```

It doesn't contain any info related to `jQuery` though. Did you get any luck by replacing the `moment` package with the npm version?

**Comment by john-osullivan** [comment]
Unfortunately, no dice.  I was originally using the NPM package instead of the Meteor one, and switching the other way didn't fix anything.  My stack trace no longer has `moment` in it, so I'm not convinced it was specifically related.  After that debugging, the stack trace now seems to go through a few unrelated components before circling back to the `jQuery is not defined` error:

![image](https://cloud.githubusercontent.com/assets/3820981/12591952/40e9aae2-c438-11e5-967b-b43a527d3a30.png)

I can't even tell where I'm using the jQuery, because the provided line numbers don't point to any jQuery code.  @eXon , @gothicn , any tips on how I might ferret out the errant use of jQuery in here?  Alternately, is there any way to make it visible from within SSR?

**Comment by eXon** [comment]
I would rather make sure jQuery is available. It is supposed to be. I'll check this when I have the time (which I don't have a lot for the past few weeks :/)

**Comment by john-osullivan** [comment]
No worries, thanks for taking a look at it!  I look forward to launching online once you've got it solved.

**Comment by john-osullivan** [comment]
Which library is responsible for binding the `global.jQuery

**Comment by john-osullivan** [comment]
Hey @eXon , another update on this.  I tried disabling SSR by commenting out the relevant code in `entry/server/entry.js` and the jQuery error went away, but a new one sprung up:

`Uncaught ReferenceError: webpackJsonp is not defined.`

I'm still trying to wrap my head around how this whole thing works, so I'm not sure where webpackJsonp is supposed to get created.  Sorry to keep bothering you about this, just trying to figure out how to get my site online.  Thank you!

**Comment by john-osullivan** [comment]
Hey @eXon , I noticed that the `meteor-webpack`, `react-router`, and `react-router-ssr` packages were all recently updated.  Do you know if those changes will affect how chunks are being loaded?

**Comment by eXon** [comment]
This has been fixed with meteor-webpack 1.0. You shouldn't get jQuery undefined now. Let me know if it works!

**Comment by john-osullivan** [comment]
jQuery is now defined, thank you!  Things still aren't working after doing the re-write to accommodate `meteor-webpack @ 1.0.2`, but I think it's because I'm using Semantic-UI.  Specifically, I'm using their Meteor integration.

The problem is that each of their files (e.g. the JS for dropdowns) returns a function which takes `(jQuery, window, document)` and then passes those values in from the environment when you do the actual require.  To be clear, the structure of their files looks like:
```
(function($, window, document, undefined){
    // Code for element...
})(jQuery, window, document);
```
This means that when the `require` gets called, it assumes there will be values in the environment for `jQuery`, `window`, and `document`.  Is there any way for me to mock up values of `window` and `document` on the server?  At this point I'm just asking for help because I'm not sure how everything works under the hood.

I only `require` and use the Semantic-UI JS files from within the componentDidMount() method, because none of them are necessary to render the initial page.  However, it seems like the code is getting loaded in during the initial render.  Is there any way to keep the server from executing `require` statements it isn't actually hitting in the code path?  If the `require` didn't happen until the page had already `Mount`ed on the client, I think this issue would disappear.

Thanks for all the help throughout this, Benoit!  I'd appreciate your advice on how to approach this, although it seems like this issue is squarely on my end and not yours.  Your libraries are excellent, I'm just trying to mash too many things together ;)

**Comment by john-osullivan** [comment]
It's finally fixed!  I'm a little embarrassed by how straightforward the final solution was, I just had to put the `require(<semantic-ui-components>)` statements inside of an if-statement keyed on `Meteor.isClient`.  Server-side rendering is now working great!  There are some issues with getting publications to load, but those issues are certainly disconnected from this one.

Again, I can't thank you enough for making these libraries and being so willing to help me work through the issues I've had.  You're a hero, +1.
