### ISSUE TITLE
integrate with React Intl v2 

### ISSUE THREAD

**Issue by ansonla3** [thereactivestack/kickstart-meteor-react-router#50]
I wonder how is it possible to integrate with React Intl v2 with the ReactRouterSSR ?
How to integrate IntlProvider with the main component ?

ReactDOM.render(
<Router history={createBrowserHistory()} routes={rootRoute} /> ,
  document.body
);

Thanks.

**Comment by minfawang** [comment]
I think the `wrapper` attribute in the client and server options of [React-Router-SSR](https://github.com/thereactivestack/meteor-react-router-ssr#clientoptions-optional) might help.

**Comment by eXon** [comment]
You can use your main top component of your route and set the <IntlProvider /> right there with the `this.props.children` within. it should work because all it needs is to set some stuff on the context
