### ISSUE TITLE
Can not specify a loader for JSON

### ISSUE THREAD

**Issue by jdanilov** [thereactivestack/kickstart-meteor-react-router#60]
Hi, every time I import dependencies that include json code, such as "cheerio" and "request" I get a startup exceptions:
`@ ./~/entities/lib/decode.js 2:16-46 sources/server.js: ./~/htmlparser2/~/entities/maps/decode.json
Module parse failed:
D:\ws\~\node_modules\htmlparser2\node_modules\entities\maps\decode.json
Line 1: Unexpected token :
You may need an appropriate loader to handle this file type.`
However I don't see a way to add a json loader to the webpack config. Could you clarify that please?

**Comment by eXon** [comment]
Have you tried adding the `webpack:json` package to your project?

**Comment by jdanilov** [comment]
Well I tried adding json-loader to the project, however it needs to be mapped to process ".json" files but it seems I can't figure the way to do so as webpack.json file is a json itself and thus doesn't support regexp to specify the file mask. Thus I can't put a loader configuration in there.

**Comment by eXon** [comment]
If you have the `webpack:json` package in your project, your config will automatically include the json extension + the loader. You don't need to configure anything.

Can you share your project or config files?

**Comment by jdanilov** [comment]
I might be missing something: can't find a reference to "webpack:json" plugin anywhere. What command adds it to the project?

**Comment by jdanilov** [comment]
Pardon, now I figured this out and it works. meteor add webpack:json. You put a lot of work in this. Thanks a lot!

**Comment by eXon** [comment]
No problem. It can be confusing, it just cannot be that easy :P
