### ISSUE TITLE
Unable to deploy with mupx

### ISSUE THREAD

**Issue by imkost** [thereactivestack/kickstart-meteor-react-router#61]
I'm trying to deploy this kickstart project with `mupx`.

`mupx setup` processes with no error, but when I do `mupx deploy` I get this:

> => Archiving failed: ENOENT: no such file or directory, stat '/tmp/b01a28dd-ebb5-4ff6-b2d8-a0fd28eb368d/bundle/programs/server/npm/react-runtime-prod/node_modules/react/node_modules/envify/node_modules/jstransform/node_modules/esprima-fb/.#README.md'

I tried to move `mup.json` out of project folder — same result.

I found discussion about the same issue https://forums.meteor.com/t/mupx-archiving-failed-enoent/15281

People suggest to downgrade React to 0.14.3. Kickstart project uses React 0.14.1. I tried to install 0.14.3 — same error occurs.

**Comment by eXon** [comment]
I got the same problem than you and it is because of your react-runtime version.

Go in your .meteor/versions file and change react-runtime, react-runtime-dev, react-runtime-prod to 0.14.3 and make sure you never update it until https://github.com/arunoda/meteor-up/issues/812 is fixed.

**Comment by imkost** [comment]
Nice! This helps. Thank you.
