### ISSUE TITLE
[documentation] Use react-router without ssr

### ISSUE THREAD

**Issue by dagatsoin** [thereactivestack/kickstart-meteor-react-router#62]
I am trying the meteor-react-router kickstarter but I wonder how to remove SSR without break the app. I build a cordova app so I don't need SSR. What must replace this piece of code in routes.jsx ?
```
ReactRouterSSR.Run(
  <Route>
    {todoRoutes}
  </Route>
);
```

**Comment by eXon** [comment]
You have two options:

1. You use react-router from `reactrouter:react-router` or NPM. You replace it with what a regular react-router app would use (`ReactDOM.render` and `<Router history={browserHistory>{/*...*/}</Router>`). For more info look at the react-router doc.
2. (much easier) just remove from server.js the `if (process.env.NODE_ENV === 'production')` block

Hope this helps

**Comment by dagatsoin** [comment]
Hi @eXon. I dis both of your options. The root component (WorldMapModule) is well displayed but the app does not load the DetailsContainer when I click on a `<Link>`.

My client.js
```
import 'app/client';
```

Here is my `client/index.js` code:
```
...
render(
      <Router history={browserHistory}>
        <Route path="/" component={App}>
          <IndexRoute component={WorldMapModule} />
          <Route path='/map' component={WorldMapModule} >
            <Route path="/entity/:id" component={DetailsContainer}/>
          </Route>
        </Route>
      </Router>,
      document.getElementById('render-target')
    );
...
```

and here is my `server.js` file:

```
import 'app/server';
```

**Comment by dagatsoin** [comment]
Ok it was a regression in my code. So do the both options like here https://github.com/thereactivestack/kickstart-meteor-react-router/issues/62#issuecomment-195735404 works for removing SSR.
