### ISSUE TITLE
Possible transpilation issue

### ISSUE THREAD

**Issue by niftykins** [thereactivestack/kickstart-meteor-react-router#63]
After cloning this repo and running it as is, the application is only able to be loaded in Chrome without erroring.

Firefox: v43.0.4 `SyntaxError: let is a reserved identifier`
Safari v9.0.3: `SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.`

I'm assuming this is an issue with the transpilation process, as updating Firefox to v44 (which enabled `const` and `let` without an opt-in) made it load fine.

**Comment by eXon** [comment]
Just looked my deployed app with Safari and it doesn't seem to be a problem. It is compiled to something that should be 100% cross-browser.

Are you using ES6 syntax within a meteor.startup.js file? (you can't)

**Comment by niftykins** [comment]
I hadn't changed anything in the repo, just clone, install, run.

But it does work without issue now, so I guess that's all that matters!
