### ISSUE TITLE
Code splitting and CSS

### ISSUE THREAD

**Issue by fuatsengul** [thereactivestack/kickstart-meteor-react-router#67]
Hello @eXon 

Probably I've got something wrong.
I've started to try this package, I've created a new folder into /src folder and created basic jsx files using todoapp as an example. But I'm pretty sure that I did not reference any CSS file in those components. and routes are different too. But the CSS file in todoapp is affecting my new components.

Is it the way it gonna be? I thought the .import.css extension tells react that to load only when I'm in those routes.

**Comment by infacq** [comment]
from the example provided, no other route than `/` only. Wait @eXon to enlighten the best way to approach it. Do you mind share your code @fuatsengul ?

**Comment by eXon** [comment]
Your CSS is going to be bundled with your JavaScript when you import them using the .import.css extension.
