### ISSUE TITLE
Issue after updating meteor and some packages 

### ISSUE THREAD

**Issue by jayasth** [thereactivestack/kickstart-meteor-react-router#68]
Cloned the repo
ran meteor in project folder 
ran npm intall
ran meteor - worked fine
checked meteor version, wanted to upgrade meteor and ran
meteor update --release 1.3-beta.16
( I noticed this -  ecmascript             upgraded from 0.1.6 to 0.4.0-beta.16)
ran meteor - it worked fine
ran meteor update - it said new versions are available following packages:

react-meteor-data 0.2.4 (0.2.5 is available)
react-runtime 0.14.3 (0.14.4 is available)
meteorhacks:fast-render 2.12.0 (2.13.0 is available)
react 0.14.3 (0.14.3_1 is available)
react-runtime-dev 0.14.3 (0.14.4 is available)
react-runtime-prod 0.14.3 (0.14.4 is available)

updated each of them manually eg. meteor update react-meteor-data@0.2.5
ran meteor - this time it's giving error:

_While determining active plugins:
   error: conflict: two packages included in the app (ecmascript and webpack:webpack)
   are both trying to handle *.js
   error: conflict: two packages included in the app (ecmascript and webpack:webpack)
   are both trying to handle *.jsx_

I can't see ecmascript anywhere in packages or package.json file, however there is ecmascript folder in .meteor/local/plugin-cache, not sure what's building it. If i remove that folder and run meteor rebuild that folder gets created again. Just wondering if anyone has come across this problem?

**Comment by genyded** [comment]
ecmascript is a meteor package and since this repo uses babel via webpack, you need to remove the ecmascript package from meteor with `meteor remove ecmascript` or comment it out or remove it from the packages file in the .meteor folder.

**Comment by eXon** [comment]
Make sure you remove ecmascript package. Webpack is doing the same job + way more anyway :)
