### ISSUE TITLE
Production mode is not working on OS X

### ISSUE THREAD

**Issue by dmitry-sher** [thereactivestack/kickstart-meteor-react-router#69]
Steps to reproduce:
```
git clone https://github.com/thereactivestack/kickstart-meteor-react-router.git
cd kickstart-meteor-react-router/
meteor update
meteor run --production
npm install
meteor run --production
```
(it asks to do npm install after first run)

Error text:
```
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While processing files with webpack:webpack (for target web.browser):
   src/client.js: ./src/TodoApp/client/css/TodoApp.import.css
   Module parse failed:
   /...../src/kickstart-meteor-react-router/src/TodoApp/client/css/TodoApp.import.css
   Line 2: Unexpected token {
   You may need an appropriate loader to handle this file type.
   | /* CSS declarations go here */
   | body {
   |   font-family: sans-serif;
   |   background-color: #315481;
   @ ./src/TodoApp/client/css/TodoApp.import.css 4:14-47
   src/client.js: ./src/TodoApp/client/css/TodoApp.import.css
....
```

The same error happens for ```meteor build```

**Comment by infacq** [comment]
same happen to me also

**Comment by tomitrescak** [comment]
Yeah, I reported it as well in the four outer project.

**Comment by infacq** [comment]
actualy what we missed?

**Comment by dmitry-sher** [comment]
Well, this issue may be a little bit outdated now, when Meteor 1.3 is released. I'll check, if it works with 1.3. 

I'm waiting eagerly for updates, we badly need production mode and builds working for our project, that's scheduled to be deployed in three weeks )

**Comment by dmitry-sher** [comment]
Hooray! The production mode on clean repo is working! Here is the commands list:

```
git clone https://github.com/thereactivestack/kickstart-meteor-react-router.git
cd kickstart-meteor-react-router/
meteor update  <--- here comes the 1.3
meteor run <-- it doesn't runs, asks for npm install
npm install
meteor npm install --save react-addons-pure-render-mixin
meteor run --production
```

checking for build for linux now...

**Comment by dmitry-sher** [comment]
But Linux build is not working, yet.

```
#meteor build ../build/ --server=http://<SERVER:PORT> --architecture os.linux.x86_64
Errors prevented bundling:                    
While linking the program:                    
error: this app is not compatible with architecture 'os.linux.x86_64'
```

**Comment by heralight** [comment]
Work well on linux with last @dmitry-sher instruction ;)

**Comment by infacq** [comment]
I hit another error

```bash
TypeError: Cannot read property 'PureRenderMixin' of undefined
```

**Comment by dmitry-sher** [comment]
@heralight what exactly is working? Did you achieved a build that's making a working bundle with, hopefully, Server-Side Rendering?

**Comment by dmitry-sher** [comment]
@infacq did you do ```meteor npm install --save react-addons-pure-render-mixin```?

**Comment by infacq** [comment]
now I have to run it like this

`meteor --settings settings.json `

because i need the `settings.json` properties. When try to `mup`, it will error.

**Comment by heralight** [comment]
@infacq I can do  $ meteor build ../build/ --architecture os.linux.x86_64

without any error...
