### ISSUE TITLE
Require react through atmosphere as well as NPM

### ISSUE THREAD

**Issue by infacq** [thereactivestack/kickstart-meteor-react-router#73]
I'm curious why do we need react at both, atmosphere package and NPM too. What's the difference

**Comment by eXon** [comment]
The NPM package is required for peerDependencies. However, now that Meteor 1.3 is out, we'll stop using the atmosphere version :)

**Comment by infacq** [comment]
so simply run `meteor remove webpack:react`?

**Comment by genyded** [comment]
Not sure where Benoit (@eXon) is, but I don't think removing webpack:react is correct since that the webpack config for react (regardless of where it's installed from). I think the Meteor package that can be removed is react-runtime if using the NPM react package.

**Comment by eXon** [comment]
The kickstarters have not been updated yet, but if you update webpack:webpack, webpack:react and reactrouter:react-router-ssr, you no longer need reac-truntime. It will use React from NPM.

You need webpack:react to configure Webpack, not to download it. It will come from NPM.

**Comment by infacq** [comment]
I think there duplication for react because I hit this error

`invariant.js:39 Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`

>If you aren't doing anything (fancy) with refs, there is a good chance that the problem is not with your refs, but rather an issue with having multiple copies of React loaded into your project. Sometimes, when you pull in a third-party module via npm, you will get a duplicate copy of the dependency library, and this can create problems.

**Comment by eXon** [comment]
Now we can get it from NPM with Meteor 1.3 :)
