### ISSUE TITLE
Kickstarts not working at all - none of them and no matter which Meteor version - PLEASE HELP

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-meteor-react-router#78]
I downloaded the repo, npm installed, ram it and it was OK. Then upgraded to Meteor 1.3 and running returns an error:

`ERROR in ./src/client.js
Module parse failed:  Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import 'TodoApp/client';
|
| import './routes';
 @ multi main`

Is there something that needs to be done in webpack config or elsewhere to make this work with 1.3?

**Comment by genyded** [comment]
Actually getting this same error if I don't update to 1.3 first. Can't run the repo as is - any idea why?

**Comment by genyded** [comment]
Here is a prettier version of the error. I am guessing something is missing in the webpack config?


```
Started MongoDB.
Errors prevented startup:

While processing files with webpack:webpack (for target os.windows.x86_32):
src/server.js: ./src/server.js
Module parse failed: C:\Users\genyd\AppData\Local\.meteor\projects\kickstart-meteor-react-router-master-orig\src\server.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import { ReactRouterSSR } from 'meteor/reactrouter:react-router-ssr';

| import 'TodoApp/server';
| 

```
Your application has errors. Waiting for file change.

**Comment by genyded** [comment]
Any ideas on this - it was opened 19 days ago and I am really stuck here...

**Comment by masato-io** [comment]
having same issue.

**Comment by genyded** [comment]
@eXon and thoughts on this? It seems to be effecting all the kickstarts (including the external mantra one) no matter what version of Meteor making all this unusable right now.

**Comment by genyded** [comment]
Benoit... you still alive??

**Comment by eXon** [comment]
You shouldn't have an error with Meteor 1.3. All kickstart projects have been fixed. Let me know if you're still having a problem with the details.

**Comment by genyded** [comment]
There is still something odd happening. With a clean download of the latest kick start (any or all of them) and Meteor 1.3.2.4 running displays:

`=> Started proxy.
=> Started MongoDB.
webpack built 411f8e5ba3cb55bea3d2 in 494ms  -
W20160508-11:33:03.254(-5)? (STDERR)
W20160508-11:33:03.255(-5)? (STDERR) C:\Users\genyd\AppData\Local\.meteor\projec
ts\kickstart-meteor-react-flowrouter-master\.meteor\local\build\programs\server\
app\server.js:59
W20160508-11:33:03.255(-5)? (STDERR)    import 'TodoApp/server';
                              //
W20160508-11:33:03.256(-5)? (STDERR)    ^^^^^^
W20160508-11:33:03.256(-5)? (STDERR) SyntaxError: Unexpected reserved word
W20160508-11:33:03.256(-5)? (STDERR)     at C:\Users\genyd\AppData\Local\.meteor
\projects\kickstart-meteor-react-flowrouter-master\.meteor\local\build\programs\
server\boot.js:278:30
W20160508-11:33:03.256(-5)? (STDERR)     at Array.forEach (native)
W20160508-11:33:03.256(-5)? (STDERR)     at Function._.each._.forEach (C:\Users\
genyd\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\de
v_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160508-11:33:03.257(-5)? (STDERR)     at C:\Users\genyd\AppData\Local\.meteor
\projects\kickstart-meteor-react-flowrouter-master\.meteor\local\build\programs\
server\boot.js:133:5`
