### ISSUE TITLE
Favicon and other static 'public' content

### ISSUE THREAD

**Issue by dmitry-sher** [thereactivestack/kickstart-meteor-react-router#88]
How to simply add files to some kind of 'public' folder, accessible by simple predictable URLs, without requiring them?

**Comment by rvetere** [comment]
mhm well the meteor built in assets solution is still working like a charm -> just make a /public folder in the root of your project.. put files in there - restart meteor and everything in there is just accessible (static served) by /my-file.png..

So if you put "my-file.png" into /my-meteor-project/public -> the img tag would just use `<img src="/my-file.png" />` ;)

Hope this helps you out

**Comment by dmitry-sher** [comment]
@rvetere yes, it works, huge thanx! I didn't realize it works only for the top-level `public` folder.

I appreciate requires and use them for all images and fonts, but for some types of static content it just should be _this_ filename. Like `favicon.ico`. Or `manifest.json`. Or something. So it's good to know there is a way.

**Comment by eXon** [comment]
For any files like favicon.ico, robots.txt and things that shouldn't be renamed, the good practice is to put it on the public folder.
